### ISSUE TITLE
Product info is not valid

### ISSUE THREAD

**Issue by heya0** [Crinibus/scraper#204]
Doesn't isupport Amazon?

ubuntu@VM-0-7-ubuntu:~/amazon/scraper$ python3 main.py -a -c arcteryx -u https://www.amazon.com/dp/B0B8MC7QVT
Adding product with category 'arcteryx' and url 'https://www.amazon.com/dp/B0B8MC7QVT'
Product info is not valid - category: 'arcteryx' - url: https://www.amazon.com/dp/B0B8MC7QVT

**Comment by heya0** [comment]
2022-12-05 19:57:25,191 : INFO : scraper.add_product : Adding product with category 'arcteryx' and url 'https://www.amazon.com/dp/B0B8MC7QVT'
2022-12-05 19:57:27,670 : ERROR : scraper.domains : Could not get all the data needed from url: https://www.amazon.com/dp/B0B8MC7QVT
Traceback (most recent call last):
  File "/home/ubuntu/amazon/scraper/scraper/domains.py", line 243, in _get_product_price
    return float(self.request_data.find("input", id="attach-base-product-price").get("value"))
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/amazon/scraper/scraper/domains.py", line 36, in get_product_info
    price = self._get_product_price()
  File "/home/ubuntu/amazon/scraper/scraper/domains.py", line 246, in _get_product_price
    self.request_data.find("span", class_="a-price a-text-price a-size-medium").span.text.replace("$", "")
AttributeError: 'NoneType' object has no attribute 'span'

**Comment by Crinibus** [comment]
Hi, I found the problem.
The bugfix will be released in a little while :)

**Comment by Crinibus** [comment]
I have released a new version with the bugfix, so I'm closing this issue.
If there is more problems, please open a new issue, thanks :)
